apiVersion: v1
kind: Secret
metadata:
  name: oidc-secret
data:
  clientID: {{ .Values.oidcSecret.clientID | b64enc | quote }}
  clientSecret: {{ .Values.oidcSecret.clientSecret | b64enc | quote }}
{{ if .Values.minioSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
data:
{{ range $key, $val := .Values.minioSecret }}
  {{ $key }}: {{ $val }}
{{ end }}
{{ end }}