apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-mongo-dashboard
  labels: {{ include "mongodb.labels" . | nindent 4 }}
    grafana_dashboard: grafana-mongodb-dashboard
  annotations:
    k8s-sidecar-target-directory: /tmp/dashboards/MongoDB Dashboards
data:
  mongodb-dashboard.json: |-
{{ .Files.Get "grafana-dashboards/dashboad.json" | indent 4 }}
