apiVersion: v2
name: superset
description: A Helm chart for superset on plural
type: application
version: 0.2.2
appVersion: "1.16.0"

dependencies:
- name: test-base
  repository: https://pluralsh.github.io/module-library
  version: 0.1.3
  condition: test-base.enabled
- name: superset
  version: 0.3.12
  repository: file://../../../../superset/helm/superset