apiVersion: apps/v1
kind: Deployment
metadata:
  name: plural-api
  labels:
{{ include "plural.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: plural-api
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plural-api
        app.kubernetes.io/instance: {{ .Release.Name }}
        plural.sh/monitoring: scrape
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: {{ .Values.api.port | quote }}
    spec:
      serviceAccountName: plural
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
    {{- end }}
      containers:
      - name: api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: plural-env
        {{ if .Values.rabbitmqCredentials.username }}
        - secretRef:
            name: plural-rabbitmq-secret
        {{ end }}
        env:
        - name: HOST
          value: {{ .Values.ingress.dns }}
        - name: DEPLOYED_AT
          value: {{ now | unixEpoch | quote }}
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.dbPasswordSecret }}
              key: postgresql-password
        ports:
        - name: http
          containerPort: {{ .Values.api.port }}
          protocol: TCP
        - name: epmd
          containerPort: 4369
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: http
        readinessProbe:
          httpGet:
            path: /health
            port: http
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plural-worker
  labels:
{{ include "plural.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: plural-worker
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plural-worker
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: plural
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
    {{- end }}
      containers:
      - name: worker
        image: "{{ .Values.worker.repository }}:{{ .Values.worker.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: plural-env
        {{ if .Values.rabbitmqCredentials.username }}
        - secretRef:
            name: plural-rabbitmq-secret
        {{ end }}
        env:
        - name: HOST
          value: {{ .Values.ingress.dns }}
        - name: DEPLOYED_AT
          value: {{ now | unixEpoch | quote }}
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.dbPasswordSecret }}
              key: postgresql-password
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plural-rtc
  labels:
{{ include "plural.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: plural-rtc
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plural-rtc
        app.kubernetes.io/instance: {{ .Release.Name }}
        plural.sh/monitoring: scrape
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: {{ .Values.api.port | quote }}
    spec:
      serviceAccountName: plural
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
    {{- end }}
      containers:
      - name: rtc
        image: "{{ .Values.rtc.repository }}:{{ .Values.rtc.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: plural-env
        {{ if .Values.rabbitmqCredentials.username }}
        - secretRef:
            name: plural-rabbitmq-secret
        {{ end }}
        env:
        - name: HOST
          value: {{ .Values.ingress.dns }}
        - name: DEPLOYED_AT
          value: {{ now | unixEpoch | quote }}
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.dbPasswordSecret }}
              key: postgresql-password
        ports:
        - name: http
          containerPort: {{ .Values.api.port }}
          protocol: TCP
        - name: epmd
          containerPort: 4369
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: http
        readinessProbe:
          httpGet:
            path: /health
            port: http
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chartmuseum
  labels:
{{ include "plural.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: chartmuseum
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chartmuseum
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: plural
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
    {{- end }}
      containers:
      - name: chartmuseum
        image: "{{ .Values.chartmuseum.repository }}:{{ .Values.chartmuseum.tag }}"
        imagePullPolicy: {{ .Values.chartmuseum.pullPolicy }}
        env:
        - name: PORT
          value: '8080'
        - name: DEPLOYED_AT
          value: {{ now | unixEpoch | quote }}
        - name: DEPTH
          value: '1'
        - name: CONTEXT_PATH
          value: '/cm'
        {{ if eq .Values.provider "aws" }}
        - name: STORAGE
          value: amazon
        {{ else }}
        - name: STORAGE
          value: {{ .Values.provider }}
        {{ end }}
        - name: STORAGE_GOOGLE_BUCKET
          value: {{ .Values.chartmuseum.bucket }}
        - name: STORAGE_GOOGLE_BUCKET
          value: {{ .Values.chartmuseum.bucket }}
        - name: STORAGE_GOOGLE_PREFIX
          value: ""
        - name: STORAGE_AMAZON_BUCKET
          value: {{ .Values.chartmuseum.bucket }}
        - name: STORAGE_AMAZON_BUCKET
          value: {{ .Values.chartmuseum.bucket }}
        - name: STORAGE_AMAZON_PREFIX
          value: ""
        - name: STORAGE_AMAZON_REGION
          value: {{ .Values.region }}
        - name: AWS_SDK_LOAD_CONFIG
          value: "1"  
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /cm/health
            port: http
        readinessProbe:
          httpGet:
            path: /cm/health
            port: http
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plural-www
  labels:
{{ include "plural.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.www.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: plural-www
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plural-www
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: www
        image: "{{ .Values.www.image }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: DEPLOYED_AT
          value: {{ now | unixEpoch | quote }}
        ports:
        - name: http
          containerPort: {{ .Values.www.port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources:
          {{- toYaml .Values.www.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}