apiVersion: batch/v1
kind: Job
metadata:
  name: plural-migration-{{ randAlphaNum 4 | lower }}
spec:
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: migrator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["/opt/app/bin/plural",  "migrate"]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: plural-env
        - secretRef:
            name: plural-migration-env
        env:
        {{ include "plural.env" . | nindent 8 }}
      restartPolicy: Never
  backoffLimit: 5