apiVersion: platform.plural.sh/v1alpha1
kind: Proxy
metadata:
  name: db
  labels:
{{ include "plural.labels" . | indent 4 }}
spec:
  type: db
  target: statefulset/plural-postgresql
  credentials:
    secret: plural-postgresql
    key: postgresql-password
    user: plural
  dbConfig:
    name: plural
    engine: postgres
    port: 5432
---
apiVersion: platform.plural.sh/v1alpha1
kind: Proxy
metadata:
  name: sh
  labels:
{{ include "plural.labels" . | indent 4 }}
spec:
  type: sh
  target: deployment/plural-api
  shConfig:
    command: /opt/app/bin/plural
    args: [remote_console]
---
apiVersion: platform.plural.sh/v1alpha1
kind: Proxy
metadata:
  name: rtcsh
  labels:
{{ include "plural.labels" . | indent 4 }}
spec:
  type: sh
  target: deployment/plural-rtc
  shConfig:
    command: /opt/app/bin/rtc
    args: [remote_console]