apiVersion: platform.plural.sh/v1alpha1
kind: SecretSync
metadata:
  name: rabbitmq-password
spec:
  name: rabbitmq-default-user
  namespace: {{ .Values.rabbitmqNamespace }}
---
apiVersion: platform.plural.sh/v1alpha1
kind: SecretSync
metadata:
  name: influxdb-auth 
spec:
  name: influxdb-auth
  namespace: {{ .Values.influxNamespace }}