default:
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
  services:
  - name: gcr.io/pluralsh/docker:19.03.13-dind
    alias: docker
  before_script:
  - until docker info; do sleep 1; done
  - gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
  - gcloud auth configure-docker -q
  - docker login -u mguarino46@gmail.com -p $PLURAL_ACCESS_TOKEN dkr.plural.sh
  - |
    function vendor_image {
      docker pull $1
      docker tag $1 gcr.io/pluralsh/$1
      docker push gcr.io/pluralsh/$1
      if [ -n "$2" ]; then
        docker tag $1 dkr.plural.sh/$2/$1
        docker push dkr.plural.sh/$2/$1
      fi
    }

  retry:
    max: 2
    when:
    - runner_system_failure

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

stages:
- push
- deploy

include:
- .gitlab-ci/bootstrap.yml
- .gitlab-ci/grafana.yml
- .gitlab-ci/monitoring.yml
- .gitlab-ci/vendor.yml
- .gitlab-ci/sentry.yml
- .gitlab-ci/plural.yml
- .gitlab-ci/postgres.yml
- .gitlab-ci/redis.yml
- .gitlab-ci/ghost.yml
- .gitlab-ci/influx.yml

.ignore-cond: &ignore-cond
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /pushed to plural/

deploy:
  image: gcr.io/pluralsh/plrl-base:latest
  stage: deploy
  <<: *ignore-cond
  only:
  - main
  before_script:
  - eval `ssh-agent -s`
  - echo "${GIT_SSH_KEY}" | tr -d '\r' | ssh-add - > /dev/null # add ssh key
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$GIT_SSH_KEY" >> ~/.ssh/id_rsa.pub
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - mkdir -p ~/.plural
  - cp $PLURAL_CONF ~/.plural/config.yml
  script:
  - make all
  - git config --global user.email mjg@plural.sh
  - git config --global user.name mjg
  - git add .
  - git commit -m "pushed to plural"
  - git remote rm origin && git remote add origin git@gitlab.plural.sh:$CI_PROJECT_PATH.git
  - git push origin HEAD:$CI_COMMIT_REF_NAME # Pushes to the same branch as the trigger
