apiVersion: platform.plural.sh/v1alpha1
kind: Proxy
metadata:
  name: scheduler
  labels:
{{ include "airflow.labels" . | indent 4 }}
spec:
  type: sh
  target: deployment/airflow-scheduler
  shConfig:
    command: /bin/sh
    args: []
---
apiVersion: platform.plural.sh/v1alpha1
kind: Proxy
metadata:
  name: worker
  labels:
{{ include "airflow.labels" . | indent 4 }}
spec:
  type: sh
  target: statefulset/airflow-worker
  shConfig:
    command: /bin/sh
    args: []
---
apiVersion: platform.plural.sh/v1alpha1
kind: Proxy
metadata:
  name: db
  labels:
{{ include "airflow.labels" . | indent 4 }}
spec:
  type: db
  target: service/airflow-master
  credentials:
    secret: airflow.plural-airflow.credentials.postgresql.acid.zalan.do
    key: password
    user: airflow
  dbConfig:
    name: airflow
    engine: postgres
    port: 5432