apiVersion: v1
kind: Secret
metadata:
  name: airflow-redis-password
stringData:
  redis-password: {{ .Values.secrets.redis_password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-ssh-config
data:
  id_rsa: {{ .Values.sshConfig.id_rsa | b64enc | quote }}
  id_rsa_pub: {{ .Values.sshConfig.id_rsa_pub | b64enc | quote }}
---
