apiVersion: plural.sh/v1alpha1
kind: Dependencies
metadata:
  application: true
  description: deploys the zalando postgres operator for the target cloud
spec:
  dependencies:
  - type: helm
    name: bootstrap
    repo: bootstrap
    version: '>= 0.5.1'
  - type: terraform
    name: aws
    repo: postgres
    version: '>= 0.1.1'
    optional: true
  - type: terraform
    name: gcp
    repo: postgres
    version: '>= 0.1.0'
    optional: true