# Default values for knative.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

observabilityConfig: {}
networkConfig: {}
loggingConfig: {}
leaderElectionConfig: {}
gcConfig: {}
featuresConfig: {}
domainConfig: {}
deploymentConfig: {}
defaultsConfig: {}
autoscalerConfig: {}
tracingConfig: {}