postgres-spilo:
  stage: push
  script:
  - docker build -f postgres/Dockerfile -t gcr.io/pluralsh/acid/spilo-13:2.0-p7 -t dkr.plural.sh/postgres/acid/spilo-13:2.0-p7 .
  - docker push gcr.io/pluralsh/acid/spilo-13:2.0-p7
  - docker push dkr.plural.sh/postgres/acid/spilo-13:2.0-p7