apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    eventing.knative.dev/release: v0.22.0
  name: eventing-webhook
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 80%
  selector:
    matchLabels:
      app: eventing-webhook
