apiVersion: v1
kind: Service
metadata:
  labels:
    eventing.knative.dev/release: v0.22.0
    role: eventing-webhook
  name: eventing-webhook
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https-webhook
      port: 443
      targetPort: 8443
  selector:
    role: eventing-webhook
