apiVersion: v1
kind: Secret
metadata:
  name: postgres-environment
  labels:
    platform.plural.sh/sync: pg
{{ include "postgres.labels" . | indent 4 }}
  annotations:
    kubed.appscode.com/sync: ""
stringData:
{{ toYaml .Values.configSecret | indent 2 }}
