apiVersion: v1
kind: Service
metadata:
  labels:
  {{ include "postgres.labels" . | nindent 4 }}
  name: postgres-operator
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    {{ include "postgres.selectorLabels" . | nindent 4 }}