{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-operator
  labels:
  {{ include "postgres.labels" . | nindent 4 }}
  annotations:
  {{ .Values.serviceAccount.annotations | toYaml | nindent 4 }}
{{ end }}