apiVersion: platform.plural.sh/v1alpha1
kind: Proxy
metadata:
  name: db
  labels:
{{ include "sentry-plural.labels" . | indent 4 }}
spec:
  type: db
  target: statefulset/sentry-sentry-postgresql
  credentials:
    secret: sentry-sentry-postgresql
    key: postgresql-password
    user: postgres
  dbConfig:
    name: sentry
    engine: postgres
    port: 5432