apiVersion: v1
kind: Secret
metadata:
  name: hydra.plural-postgres-hydra.credentials.postgresql.acid.zalan.do
  labels:
{{ include "hydra-plural.labels" . | indent 4 }}
stringData:
  username: hydra
  password: {{ .Values.postgres.password }}
