apiVersion: v2
name: mlflow
description: A Helm chart for Kubernetes
type: application
version: 0.1.3
appVersion: "0.1.2"
dependencies:
- name: mlflow-operator
  version: 0.1.1
  repository: https://pluralsh.github.io/plural-helm-charts
