apiVersion: v2
name: mlflow
description: A Helm chart for Kubernetes
type: application
version: 0.1.4
appVersion: "0.1.3"
dependencies:
- name: mlflow-operator
  version: 0.1.2
  repository: https://pluralsh.github.io/plural-helm-charts
