apiVersion: v1
data:
  artifactRepository: |
    archiveLogs: true
    s3:
      bucket: pipelines-bucket
      keyPrefix: pipelines
      endpoint: s3.amazonaws.com
      region: us-east-2
      insecure: false
      accessKeySecret:
        name: pipelines-s3-secret
        key: username
      secretKeySecret:
        name: pipelines-s3-secret
        key: password
      keyFormat: {{ printf "\"pipelines/{{workflow.namespace}}/{{workflow.name}}/{{pod.name}}\"" }}
  containerRuntimeExecutor: pns
  executor: |
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 0.01
        memory: 32Mi
      limits:
        cpu: 0.5
        memory: 512Mi
kind: ConfigMap
metadata:
  labels: {{- include "pipelines.labels" . | nindent 4 }}
  name: {{ include "pipelines.fullname" . }}-argo-workflow-controller
  namespace: kubeflow
