apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipelines.fullname" . }}-argo-workflow-controller
  namespace: kubeflow
  labels:
    {{- include "pipelines.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pipelines.argoWorkflowControllerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        prometheus.io/port: "9090"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pipelines.argoWorkflowControllerSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pipelines.serviceAccountName" . }}-argo-workflow-controller
      securityContext:
        # runAsNonRoot: true # TODO: Fix runAsNonRoot
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-argo-workflow-controller
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.argoWorkflowController.image.repository }}:{{ .Values.argoWorkflowController.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.argoWorkflowController.image.pullPolicy }}
          args:
            - --configmap
            - {{ include "pipelines.fullname" . }}-argo-workflow-controller
            - --executor-image
            - gcr.io/ml-pipeline/argoexec:v2.12.9-license-compliance
          command:
            - workflow-controller
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        kubernetes.io/os: linux
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
