apiVersion: batch/v1
kind: Job
metadata:
  name: console-migration-{{ randAlphaNum 4 | lower }}
spec:
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: migrator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["/opt/app/bin/console",  "migrate"]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: console-env
        - secretRef:
            name: console-migration-env
        env:
        {{ include "console.env" . | nindent 8 }}
        volumeMounts:
        - name: console-ssh
          mountPath: "/root/.ssh"
        - name: console-conf
          mountPath: "/root/.plural"
      volumes:
        - name: console-ssh
          secret:
            defaultMode: 384
            secretName: console-ssh
        - name: console-conf
          secret:
            secretName: console-conf
      restartPolicy: Never
  backoffLimit: 5