apiVersion: v1
kind: Pod
metadata:
  name: {{ include "common.names.fullname" . }}-bootloader-{{ randAlphaNum 6 }}
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
  {{- if .Values.bootloader.podAnnotations }}
  annotations:
  {{- include "common.tplvalues.render" (dict "value" .Values.bootloader.podAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  serviceAccountName: {{ include "airbyte.serviceAccountName" . }}
  restartPolicy: Never
  containers:
    - name: airbyte-bootloader-container
      image: {{ include "airbyte.bootloaderImage" . }}
      imagePullPolicy: "{{ .Values.bootloader.image.pullPolicy }}"
      envFrom:
      - secretRef:
          name: airbyte-env
      env:
      - name: DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: {{ include "airbyte.postgresql.secretName" . }}
            key: {{ include "airbyte.database.existingsecret.key" . }}
