apiVersion: v2
name: monitoring
description: A Helm chart for Kubernetes
type: application
version: 0.1.1
appVersion: "0.1.0"
dependencies:
- name: kube-prometheus-stack
  version: 17.1.0
  repository: https://prometheus-community.github.io/helm-charts
- name: loki-stack
  version: 0.40.1
  repository: https://grafana.github.io/loki/charts
