apiVersion: v2
name: sentry
description: A Helm chart for Kubernetes
type: application
version: 0.1.5
appVersion: "1.16.0"

dependencies:
- name: sentry
  version: 11.3.0
  repository: file://../../../../sentry-charts/sentry