# Default values for sentry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

sentry:
  serviceAccount:
    name: sentry

  postgresql:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  metrics:
    image:
      repository: gcr.io/piazzaapp/prom/statsd-exporter
      tag: v0.20.2
    enabled: true
    serviceMonitor:
      enabled: true

  rabbitmq:
    enabled: false
    host: rabbitmq.rabbitmq

  nginx:
    enabled: false

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
  
  sentry:
    web:
      autoscaling:
        enabled: true
    worker:
      autoscaling:
        enabled: true
    ingestConsumer:
      autoscaling:
        enabled: true

  snuba:
    autoscaling:
      enabled: true

  symbolicator:
    autoscaling:
      enabled: true

  clickhouse:
    clickhouse:
      image: 'gcr.io/piazzaapp/yandex/clickhouse-server'
      imageVersion: '20.8.9.6'
      init:
        image: 'gcr.io/piazzaapp/busybox'
        imageVersion: latest
    