apiVersion: plural.sh/v1alpha1
kind: Dependencies
metadata:
  description: sentry kubernetes secret exports
  version: 0.1.0
spec:
  dependencies:
  - name: aws-bootstrap
    repo: bootstrap
    type: terraform
    version: '>= 0.1.1'
  providers:
  - aws
  - gcp
  - azure

  outputs:
    rabbitmq_password: rabbitmq_password
    rabbitmq_username: rabbitmq_username
    redis_password: redis_password