name: aws-grafana
description: Installs grafana on an EKS cluster
provider: AWS
dependencies:
- repo: bootstrap
  name: aws-k8s
sections:
- name: grafana
  items:
  - type: TERRAFORM
    name: aws
    configuration: []
  - type: HELM
    name: grafana
    configuration:
    - name: hostname
      documentation: FQDN to use for your grafana installation
      type: STRING
  