name: gcp-grafana
description: Installs grafana on a GKE cluster
provider: GCP
oidcSettings:
  authMethod: POST
  uriFormat: https://{domain}/login/generic_oauth
  domainKey: hostname
dependencies:
- repo: bootstrap
  name: gcp-kubernetes
sections:
- name: grafana
  items:
  - type: TERRAFORM
    name: gcp
    configuration: []
  - type: HELM
    name: grafana
    configuration:
    - name: hostname
      documentation: FQDN to use for your grafana installation
      type: STRING
  