apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  labels: {{- include "serving.labels" . | nindent 4 }}
  name: {{ include "serving.fullname" . }}-webhook
  namespace: kubeflow
spec:
  action: ALLOW
  rules:
    - {}
  selector:
    matchLabels:
      {{- include "serving.controllerSelectorLabels" . | nindent 6 }}
