apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels: {{- include "serving.labels" . | nindent 4 }}
  name: {{ include "serving.fullname" . }}-controller-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "serving.fullname" . }}-controller-cluster-role
subjects:
  - kind: ServiceAccount
    namespace: kubeflow
    name: {{ include "serving.serviceAccountName" . }}-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels: {{- include "serving.labels" . | nindent 4 }}
  name: {{ include "serving.fullname" . }}-proxy-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kfserving-proxy-role
subjects:
  - kind: ServiceAccount
    namespace: kubeflow
    name: {{ include "serving.serviceAccountName" . }}-controller
