apiVersion: v1
kind: Service
metadata:
  name: kfserving-webhook-server-service
  labels:
    {{- include "serving.labels" . | nindent 4 }}
  namespace: kubeflow
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.controller.service.webhook.port }}
      targetPort: webhook
      protocol: TCP
      name: https-webhook
    - port: {{ .Values.controller.service.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "serving.controllerSelectorLabels" . | nindent 4 }}
