
eck-operator:
  managedNamespaces: []

  installCRDs: false

  createClusterScopedResources: true

  webhook:
    enabled: true

  podAnnotations:
    sidecar.istio.io/inject: "true"
    traffic.sidecar.istio.io/includeInboundPorts: "*"
    traffic.sidecar.istio.io/excludeInboundPorts: "9443"

  podMonitor:
    enabled: true

  config:
    metricsPort: 9191

elasticsearch:
  nodes: 3
  resources:
    requests:
      memory: 2Gi
      cpu: 1
  storage: 50Gi
  version: '7.13.2'

kibana:
  enabled: true
  version: 7.13.2
  resources:
    requests:
      memory: 500Mi
      cpu: 0.5
apm:
  enabled: false
filebeat:
  enabled: false
metricbeat:
  enabled: false