apiVersion: v1
kind: Service
metadata:
  name: {{ include "pipelines.fullname" . }}-api-server
  namespace: kubeflow
  labels:
    {{- include "pipelines.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.apiServer.service.http.port }}
      targetPort: http-api-server
      protocol: TCP
      name: http-api-server
    - port: {{ .Values.apiServer.service.grpc.port }}
      targetPort: grpc-api-server
      protocol: TCP
      name: grpc-api-server
  selector:
    {{- include "pipelines.apiServerSelectorLabels" . | nindent 4 }}
