apiVersion: v1
kind: Service
metadata:
  name: ghost
  labels:
    app: ghost
{{ include "ghost.labels" . | indent 4 }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: ghost
    app.kubernetes.io/instance: {{ .Release.Name }}