apiVersion: v2
name: grafana
description: A Helm chart for grafana on plural
type: application
version: 0.1.1
appVersion: "1.16.0"

dependencies:
- name: grafana
  version: 6.9.1
  repository: https://grafana.github.io/helm-charts