apiVersion: v2
name: grafana
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
- name: grafana
  version: 6.9.1
  repository: https://grafana.github.io/helm-charts