apiVersion: plural.sh/v1alpha1
kind: Dependencies
metadata:
  description: postgres azure setup
  version: 0.1.15
spec:
  dependencies:
  - name: azure-bootstrap
    repo: bootstrap
    type: terraform
    version: '>= 0.1.1'
  - name: azure
    repo: minio
    type: terraform
    version: '>= 0.1.5'
  providers:
  - azure
