apiVersion: v2
name: kubecost
description: chart for deploy kubecost
type: application
version: 0.1.11
appVersion: "1.85.110"
dependencies:
- name: cost-analyzer
  version: 1.85.1
  repository: https://kubecost.github.io/cost-analyzer/
