apiVersion: v1
kind: Secret
metadata:
  name: calendso-env
  labels:
{{ include "calendso.labels" . | indent 4 }}
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  NODE_TLS_REJECT_UNAUTHORIZED: '0'
  BASE_URL: {{ .Values.secrets.baseUrl }}
  {{ if .Values.secrets.googleApiCredentials }}
  GOOGLE_API_CREDENTIALS: {{ .Values.secrets.googleApiCredentials }}
  {{ end }}
  {{ if .Values.secrets.zoomClientId }}
  ZOOM_CLIENT_ID: {{ .Values.secrets.zoomClientId }}
  {{ end }}
  {{ if .Values.secrets.zoomClientSecret }}
  ZOOM_CLIENT_SECRET: {{ .Values.secrets.zoomClientSecret }}
  {{ end }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret }}
  CALENDSO_ENCRYPTION_KEY: {{ .Values.secrets.calendsoEncryptionKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: calendso.plural-calendso.credentials.postgresql.acid.zalan.do
  labels:
{{ include "calendso.labels" . | indent 4 }}
stringData:
  username: calendso
  password: {{ .Values.postgres.password }}