apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-grafana-datasource
  labels:
    grafana_datasource: '1'
    {{ include "grafana-plural.labels" . | nindent 4 }}
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://monitoring-prometheus.monitoring:9090
    - name: Loki
      type: loki
      access: proxy
      orgId: 1
      url: http://monitoring-loki.monitoring:3100
