apiVersion: v2
name: ghost
description: A Helm chart for Kubernetes
type: application
version: 0.1.11
appVersion: "1.16.0"

dependencies:
- name: ghost
  version: 14.0.12
  repository: https://charts.bitnami.com/bitnami