replicaCount: 1

db:
  rootPassword: replace
  password: replace
  name: ghost
  username: ghost


ghost:
  ghostEnableHttps: true
  image:
    registry: dkr.plural.sh/ghost
  ingress:
    enabled: true
    tls: true
    annotations:
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'