apiVersion: v1
data:
  namespace-labels.yaml: |
    # Below is a list of labels to be set by default.
    #
    # To add a namespace label, use `key: 'value'`, for example:
    # istio.io/rev: 'asm-191-1'
    #
    # To remove a namespace label, use `key: ''`. For example:
    # istio-injection: ''
    #
    # Profile controller will not replace a namespace label if its key already
    # exists. If you want to override the value of a previously applied label, you
    # need to:
    # 1. Remove the label by using `key: ''` and deploy.
    # 2. Add the label by using `key: 'value'` and deploy.
    #
    {{- toYaml .Values.config.namespaceLables | nindent 4 }}
kind: ConfigMap
metadata:
  labels:
    kustomize.component: profiles
  name: {{ include "profile-controller.fullname" . }}-namespace-labels-data
  namespace: kubeflow
---
apiVersion: v1
data:
  ADMIN: {{ .Values.config.adminUserEmail }}
  USERID_HEADER: {{ .Values.global.userIDHeader }}
  USERID_PREFIX: {{ .Values.global.userIDPrefix | quote }}
  ISSUER: {{ .Values.global.oidcIssuer }}
  JWKSURI: {{ .Values.global.jwksURI }}
  PIPELINES_BUCKET: {{ .Values.config.pipelinesBucket }}
  WORKLOAD_IDENTITY: ""
  DEFAULTNAMESPACELABELSPATH: /etc/profile-controller/namespace-labels.yaml
kind: ConfigMap
metadata:
  labels: {{- include "profile-controller.labels" . | nindent 4 }}
  name: {{ include "profile-controller.fullname" . }}-config
  namespace: kubeflow
---
apiVersion: v1
data:
  network-policy.yaml: |
{{ .Files.Get "profile-templates/network-policy.yaml" | indent 4 }}
  test-template.yaml: |
{{ .Files.Get "profile-templates/test-template.yaml" | indent 4 }}
kind: ConfigMap
metadata:
  labels: {{- include "profile-controller.labels" . | nindent 4 }}
  name: {{ include "profile-controller.fullname" . }}-templates
  namespace: kubeflow
