apiVersion: v1
kind: Secret
metadata:
  labels:
    serving.knative.dev/release: v0.24.0
  name: domainmapping-webhook-certs
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    networking.knative.dev/ingress-provider: istio
    serving.knative.dev/release: v0.24.0
  name: net-istio-webhook-certs
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    serving.knative.dev/release: v0.24.0
  name: webhook-certs
  namespace: {{ .Release.Namespace }}
