apiVersion: v1
kind: Secret
metadata:
  name: objectstore-connection
stringData:
  connection: {{ toYaml .Values.railsConnection | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-connection
stringData:
  config: {{ toYaml .Values.registryConnection | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-root-pwd
stringData:
  password: {{ .Values.rootPassword }}