# Default values for hasura.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

hasura:
  ingress:
    enabled: true
    # ingressClassName: nginx
    annotations:
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: "nginx"
      # Extend timeout to allow long running queries.
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "300"

postgres:
  password: CHANGEME
  replicas: 1
  storage:
    size: 25Gi
  resources: {}
  default:
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: "2"
        memory: 1Gi
