apiVersion: v2
name: gitlab
description: A Helm chart for gitlab on plural
type: application
version: 0.1.35
appVersion: "1.16.0"

dependencies:
- name: gitlab
  version: 4.11.4
  repository: https://charts.gitlab.io/