application: true
dependencies:
- type: helm
  name: bootstrap
  repo: bootstrap
  version: '>= 0.5.1'
- type: terraform
  name: aws
  repo: plural
  version: '>= 0.1.1'
  optional: true
- type: terraform
  name: gcp
  repo: plural
  version: '>= 0.1.1'
  optional: true