replicaCount: 2

rbac:
  serviceAccountAnnotations: {}

image:
  repository: dkr.plural.sh/plural/plural
  tag: '0.1.1'
  pullPolicy: Always

rtc:
  repository: dkr.plural.sh/plural/rtc
  tag: '0.1.1'

worker:
  repository: dkr.plural.sh/plural/worker
  tag: '0.1.1'

www:
  image: dkr.plural.sh/plural/plural-www
  tag: '0.1.1'
  port: 80

cron:
  image: dkr.plural.sh/plural/cron
  tag: '0.1.1'

imagePullSecrets:
- name: plural-creds

provider: aws
region: us-east-1

api:
  port: 4000
  bucket: plural-assets

dbPasswordSecret: plural-postgresql
rabbitPasswordSecret: plural-rabbitmq

crons:
- cronName: plural-dkr-scan
  cronModule: Task.Docker
  crontab: "0 0 * * *"
  envVars: []

chartmuseum:
  resources: {}
  replicaCount: 1
  rbac:
    serviceAccountAnnotations: {}
  repository: dkr.plural.sh/plural/chartmuseum
  tag: v0.13.2
  bucket: plural-charts
  pullPolicy: Always

registry:
  replicaCount: 1
  podAnnotations: {}
  podLabels: {}
  podDisruptionBudget: {}
  nodeSelector: {}
  tolerations: []
  rbac:
    serviceAccountAnnotations: {}

  persistence:
    accessMode: ReadWriteOnce
    enabled: false
    size: 10Gi

  securityContext:
    enabled: false
    runAsUser: 1000
    fsGroup: 1000

  secrets:
    haSharedSecret: ""

  image: 
    repository: gcr.io/piazzaapp/registry
    tag: 2.7.2

  configData:
    version: 0.1
    notifications:
      endpoints:
      - name: plural
        url: http://plural-api:4000/dkr/callback
        timeout: 500ms
        threshold: 5
        backoff: 1s
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
    prometheus:
      enabled: true
    auth:
      token:
        realm: plural.piazza.app/dkr
        service: plural.piazza.app/dkr
        issuer: plural.piazza.app
        rootcertbundle: /etc/docker/registry/cert.pem
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3

postgresql:
  image:
    registry: gcr.io
    repository: piazzaapp/postgres
    tag: 11.7.0-debian-10-r9
  metrics:
    enabled: true
    image:
      registry: gcr.io
      repository: piazzaapp/postgres-exporter
      tag: 0.8.0
    serviceMonitor:
      enabled: true
  postgresqlExtendedConf:
    max_connections: 100
  postgresqlUsername: plural
  postgresqlDatabase: plural

rabbitmqCredentials:
  namespace: "rabbitmq"

rabbitmq:
  metrics:
    enabled: true

influxdb:
  resources:
    requests:
      memory: 256Mi
      cpu: 0.2
  env:
  - name: INFLUXDB_DB
    value: plural
  setDefaultUser:
    enabled: true
    user:
      username: plural
      password: null

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  dns: app.plural.sh
  dkr_dns: dkr.plural.sh
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-path: /socket
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
  
resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
