# docker run -d -it -v /path/on/host:/data -e EULA=TRUE -p 25565:25565 --name mc itzg/minecraft-server
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft-server
  labels:
    app: minecraft-server
    {{ include "minecraft.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: minecraft-headless
  selector:
    matchLabels:
      app: minecraft-server
  volumeClaimTemplates:
  - metadata:
      name: minecraft-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.volume.storage }}
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
      - name: minecraft-server
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        resources:
        {{ toYaml .Values.resources | nindent 10 }}
        env:
          - name:  EULA
            value: 'TRUE'
          - name: MODE
            value: {{ .Values.minecraft.gamemode }}
          - name: MOTD
            value: {{ .Values.minecraft.motd }}
          {{ if .Values.minecraft.type }}
          - name: TYPE
            value: {{ .Values.minecraft.type }}
          {{ end }}
          - name: ALLOW_FLIGHT
            value: 'TRUE'
        ports:
        - containerPort: {{ .Values.minecraft.port }}
          name: minecraft
        volumeMounts:
          - name: minecraft-data
            mountPath:  /data
        readinessProbe:
          exec:
            command:
            - mc-monitor
            - status
          initialDelaySeconds: 240
          periodSeconds: 30
        livenessProbe:
          exec:
            command:
            - mc-monitor
            - status
          initialDelaySeconds: 240
          periodSeconds: 30