apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-touca-api
  name: {{ .Release.Name }}-touca-api
  namespace: {{ .Release.Name }}-touca
spec:
  replicas: {{ .Values.toucaApi.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-touca-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-touca-api
    spec:
      containers:
      - image: {{ .Values.global.dockerRepoName | default "touca" | lower }}/touca-api:{{ .Values.global.dockerImageTag }}
        name: {{ .Release.Name }}-touca-api
        envFrom:
        - secretRef:
            name: touca-env
        env:
        - name: ENV_FILE
          value: prod
        - name: WEBAPP_ROOT
          value: "http://{{ .Release.Name }}-touca-app"
        - name: MINIO_HOST
          value: {{ .Release.Name }}-touca-minio
        - name: MONGO_HOST
          value: mongo-svc.{{ .Values.mongoNamespace }}
        - name: REDIS_HOST
          value: {{ .Release.Name }}-touca-redis
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-admin-admin
              key: username
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-admin-admin
              key: password
        - name: LOG_LEVEL
          value: silly
      #   volumeMounts: # why is this being created?
      #   - mountPath: /opt/local/logs/api
      #     name: api-volume
      # volumes:
      # - name: api-volume
      #   persistentVolumeClaim:
      #     claimName: touca-ebs